###POST blogs WITH USERID
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvc3RtYW4iLCJpZCI6IjY1N2IwZGRmZjJjZGUzNGJhMzFiOGQxZSIsImlhdCI6MTcwMjU2MzMxN30.PZvfPuShEc-droSEm20Ue0RabMHUdCpurHvwVvbdNlM

{
    "title": "Blog with Authorization: ",
    "author": "Mr Authorized",
    "url": "https://1stBlog.com/",
    "likes": 0
} 
### POST blogs WITHOUT USERID
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "My first Blog___no user specified",
    "author": "Me",
    "url": "https://1stBlog_nouser.com/",
    "likes": 0
} 
###
GET http://localhost:3001/api/blogs HTTP/1.1
###
GET http://localhost:3001/api/blogs/656f069711dafc9bdfb5809d HTTP/1.1
### 
DELETE http://localhost:3001/api/blogs/656f3dfcdd353c21e73484ac HTTP/1.1
###
PUT http://localhost:3001/api/blogs/65773f640a0475818945f0d8 HTTP/1.1
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 120,
  "id": "65773f640a0475818945f0d8"
}


