###POST blogs WITH authorization token
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJfbnVtYmVyMSIsImlkIjoiNjU3Yzk1ZDUzOTBkZWEyOWY4MjBiZWQyIiwiaWF0IjoxNzAyNjYzNjYwfQ.-hISsZKi85Tns9XZ0nIyFXTbTZoejLBvfB2AcEGLIk4

{
    "title": "TESTESTEST",
    "author": "User n1",
    "url": "https://1stBlog.com/",
    "likes": 100.000
} 

### DELETE with authorization token
DELETE http://localhost:3001/api/blogs/657c96de8cab31b8e1e46c43 HTTP/1.1
Authorization: Bearer xyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJfbnVtYmVyMSIsImlkIjoiNjU3Yzk1ZDUzOTBkZWEyOWY4MjBiZWQyIiwiaWF0IjoxNzAyNjYzNjYwfQ.-hISsZKi85Tns9XZ0nIyFXTbTZoejLBvfB2AcEGLIk4

### POST blogs WITHOUT USERID
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "My first Blog___no user specified",
    "author": "Me",
    "url": "https://1stBlog_nouser.com/",
    "likes": 0
} 
###
GET http://localhost:3001/api/blogs HTTP/1.1
###
GET http://localhost:3001/api/blogs/656f069711dafc9bdfb5809d HTTP/1.1
### 
DELETE http://localhost:3001/api/blogs/656f3dfcdd353c21e73484ac HTTP/1.1
###
PUT http://localhost:3001/api/blogs/65773f640a0475818945f0d8 HTTP/1.1
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 120,
  "id": "65773f640a0475818945f0d8"
}


