###POST blogs WITH authorization token
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title": "Blog with Authorization: 100",
    "author": "Mr Authorized",
    "url": "https://1stBlog.com/",
    "likes": 0
} 

### DELETE with authorization token
DELETE http://localhost:3001/api/blogs/657c7956f182f13610944bfa HTTP/1.1
Authorization: Bearer 

### POST blogs WITHOUT USERID
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "My first Blog___no user specified",
    "author": "Me",
    "url": "https://1stBlog_nouser.com/",
    "likes": 0
} 
###
GET http://localhost:3001/api/blogs HTTP/1.1
###
GET http://localhost:3001/api/blogs/656f069711dafc9bdfb5809d HTTP/1.1
### 
DELETE http://localhost:3001/api/blogs/656f3dfcdd353c21e73484ac HTTP/1.1
###
PUT http://localhost:3001/api/blogs/65773f640a0475818945f0d8 HTTP/1.1
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 120,
  "id": "65773f640a0475818945f0d8"
}


