POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "MortiDiFame2 - la vendetta",
  "author": "Giustiziere Maskerato",
  "url": "www.maledettiiiiii.com",
  "likes": 15923
} 
###
GET http://localhost:3001/api/blogs HTTP/1.1