POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/"
} 


###
GET http://localhost:3001/api/blogs HTTP/1.1
###
GET http://localhost:3001/api/blogs/656f069711dafc9bdfb5809d HTTP/1.1
### 
DELETE http://localhost:3001/api/blogs/657710efe6cde63d09743cca HTTP/1.1



